language: scala
jdk: oraclejdk8
sudo: required
dist: trusty
before_install:
- curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -
script:
- sbt run
